version: '3'

services:
  web:
    image: praqma/network-multitool
    networks:
      frontend:
        aliases:
          - web
  app:
    image: praqma/network-multitool
    networks:
      frontend:
        aliases:
          - app
      backend:
        aliases:
          - app
  db:
    image: praqma/network-multitool
    networks:
      backend:
        aliases:
          - db

networks:
  frontend:
  backend: